Fix broken pipe issue
Piping output from ipwrangle to tools like head/tail would result in:

```Traceback (most recent call last):
  File "/usr/local/bin/ipexpand", line 8, in <module>
    sys.exit(expand_main())
  File "/usr/local/lib/python3.7/site-packages/ipwrangle/ipwrangle.py", line 24, in expand_main
    [print(ip) for ip in IPNetwork(line)]
  File "/usr/local/lib/python3.7/site-packages/ipwrangle/ipwrangle.py", line 24, in <listcomp>
    [print(ip) for ip in IPNetwork(line)]
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe```

Updated version no longer does this.